USE [master]
GO

/****** Object:  Database [MMTShop]    Script Date: 3.12.2020 21:45:48 ******/
CREATE DATABASE [MMTShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MMTShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MMTShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MMTShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MMTShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MMTShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MMTShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MMTShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MMTShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MMTShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MMTShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [MMTShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MMTShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MMTShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MMTShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MMTShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MMTShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MMTShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MMTShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MMTShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MMTShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MMTShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MMTShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MMTShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MMTShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MMTShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MMTShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MMTShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MMTShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MMTShop] SET  MULTI_USER 
GO

ALTER DATABASE [MMTShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MMTShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MMTShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MMTShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MMTShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MMTShop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MMTShop] SET  READ_WRITE 
GO


